name: Create release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
      - name: Install dependencies
        run: sudo apt-get install -y topgit
      - name: Create artefact
        run: |
          tg populate --remote
          tg patch | bzip2 > lua-cmake-${{ github.ref }}.patch.bz2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload artefact
        id: upload-artefact
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lua-cmake-${{ github.ref }}.patch.bz2
          asset_name: lua-cmake-${{ github.ref }}.patch.bz2
          asset_content_type: application/x-bzip

